### ISSUE TITLE
Cancel ongoing skip when current clip ends

### ISSUE THREAD

**Issue by ldesgoui** [IAmThermite/TF2Frags-stream#7]
ATM a clip could receive 8/10 votes for a skip and end, allowing the next clip to get skip with only 2 votes

**Comment by IAmThermite** [comment]
I hope that isn't the case as I reset the skip after it has completed, see https://github.com/IAmThermite/TF2Frags-stream/blob/master/twitch.js#L72 however if that is the stream behaviour then I will investigate

**Comment by ldesgoui** [comment]
The behavior you just linked works fine, it's just that the skips don't reset when a clip ends normally

**Comment by IAmThermite** [comment]
The skip will reset after 20 seconds, due to the way I have done the whole thing there isn't a way for the twitch bot to detect if the clip has been changed. Don't think there is an elegant way to allow it to do so unfortunately. Ill have a think about a better way to integrate them though.
